set(COMPONENT_PATH ${INSTALL_DIR_ABSOLUTE})
list(APPEND CMAKE_PREFIX_PATH ${COMPONENT_PATH})

set(COMPONENT_NAME anari-visrtx)

ExternalProject_Add(${COMPONENT_NAME}
  PREFIX ${COMPONENT_NAME}
  DOWNLOAD_DIR ${COMPONENT_NAME}
  STAMP_DIR ${COMPONENT_NAME}/stamp
  SOURCE_DIR ${COMPONENT_NAME}/src
  BINARY_DIR ${COMPONENT_NAME}/build
  URL "https://github.com/NVIDIA/VisRTX/archive/refs/tags/v0.9.0.zip"
  PATCH_COMMAND "${GIT_EXECUTABLE};--git-dir=;apply;${CMAKE_CURRENT_SOURCE_DIR}/visrtx_v0.9.0.patch"
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${COMPONENT_PATH}
    -DCMAKE_CUDA_ARCHITECTURES=OFF
    -DCMAKE_PREFIX_PATH=${OptiX_INSTALL_DIR}
)

ExternalProject_Add_StepDependencies(${COMPONENT_NAME} configure anari)
